---
- name: 部署ceph
  hosts: ceph1,ceph2,ceph3
  become: true
  vars:
    domain: mslinfo.lan
    ceph1:
      ip: 10.0.30.101
      name: ceph1
    ceph2:
      ip: 10.0.30.102
      name: ceph2
    ceph3:
      ip: 10.0.30.103
      name: ceph3
    ceph_password: Mao3long
  tasks:
    ######
    - name: 配置ceph软件包源
      block:
        - name: 配置hosts文件（所有节点）
          ansible.builtin.lineinfile:
            path: /etc/hosts
            regexp: "{{ item.name }}.{{ domain }}"
            line: "{{ item.ip }} {{item.name}}.{{ domain }} {{ item.name }}"
          loop:
            - "{{ ceph1 }}"
            - "{{ ceph2 }}"
            - "{{ ceph3 }}"

        - name: 启用ceph仓库和依赖的基础工具
          ansible.builtin.package:
            name:
              - epel-release
              - centos-release-ceph-tentacle
              - chrony
              - python3-jinja2
              - curl
              - podman
              - wget
            state: present
          become: true
          changed_when: false
        - name: 配置时间同步（启动chronyd服务）
          ansible.builtin.systemd:
            name: chronyd
            state: restarted
            enabled: true
        - name: 配置防火墙
          when: ansible_os_family in ['RedHat'] and false
          ansible.posix.firewalld:
            port: "{{ item }}"
            permanent: true
            state: enabled
            zone: public
            immediate: true
          loop:
            - 3300/tcp
            - 6789/tcp
            - 6800-7300/tcp
        - name: 安装ceph软件包
          ansible.builtin.dnf:
            name:
              - cephadm
              - ceph-common
            state: present
    ######
    - name: 配置第一个Monitor节点（node101)
      when: inventory_hostname == "{{ ceph1.name }}"
      block:
        - name: 判断ceph.pub文件是否存在
          ansible.builtin.stat:
            path: /etc/ceph/ceph.pub
          register: ceph_pub_file
          changed_when: false
        - name: 检查ceph.pub文件是否存在
          ansible.builtin.debug:
            var: ceph_pub_file.stat
        - name: 初始化第一个节点
          when: not ceph_pub_file.stat.exists | default(false)
          ansible.builtin.shell: |
            cephadm bootstrap --mon-ip "{{ ceph1.ip }}" \
            --cluster-network 10.0.30.0/24 \
            --initial-dashboard-user admin \
            --initial-dashboard-password "{{ ceph_password }}" \
            --dashboard-password-noupdate
          changed_when: "'Bootstrap successful' in bootstrapresult.stdout"
    - name: 添加节点
      block:
        - name: 读取ceph.pub公钥内容
          ansible.builtin.slurp:
            src: /etc/ceph/ceph.pub
          register: ceph_pub_data
          delegate_to: ceph1
          run_once: true
        - name: 写入root认证公钥
          ansible.posix.authorized_key:
            key: "{{ ceph_pub_data['content'] | b64decode }}"
            user: root
            state: present
            exclusive: false
