---
- name: 安装chrony服务
  hosts: all
  become: true
  vars:
    timezone: "Asia/Shanghai"
    timeserver:
      - name: "ntp.tencent.com"
      - name: "ntp.aliyun.com"

  tasks:
    - name: 设置时区为Asia/Shanghai
      community.general.timezone:
        name: "{{ timezone }}"
      changed_when: true
      become: true
    - name: 安装chrony
      ansible.builtin.package:
        name: chrony
        state: present
      become: true
    - name: 设置中国ntp服务器
      when: ansible_os_family == "Debian"
      ansible.builtin.file:
        path: /etc/chrony/sources.d/cn-ntp.sources
        owner: root
        group: root
        mode: '0644'
        state: touch
      become: true
    - name: 添加中国ntp服务器源
      when: ansible_os_family == "Debian"
      ansible.builtin.lineinfile:
        path: /etc/chrony/sources.d/cn-ntp.sources
        regexp: "^server {{ item.name }}"
        line: "server {{ item.name }} iburst minpoll 4 maxpoll 10"
        state: present
        create: false
      loop: "{{ timeserver }}"
      become: true
    - name: 添加中国ntp服务器源
      when: ansible_os_family == "RedHat"
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        regexp: "^server {{ item.name }}"
        line: "server {{ item.name }} iburst minpoll 4 maxpoll 10"
        state: present
        create: false
      loop: "{{ timeserver }}"
      become: true
    - name: 启动chronyd服务
      ansible.builtin.systemd:
        name: chronyd
        enabled: true
        state: restarted
        daemon_reload: true
      become: true
