---
- name: 安装haproxy
  hosts: ha1,ha2
  vars:
    service: haproxy
  tasks:
    - name: 在RHEL系统上安装{{ service }}
      when: ansible_os_family == 'RedHat'
      block:
        - name: 安装{{ service }}
          ansible.builtin.dnf:
            name:
              - "{{ service }}"
              - keepalived
            state: present
          become: true
        - name: 配置{{ service }}
          ansible.builtin.copy:
            dest: /etc/{{ service }}/conf.d/
            content: |
              {{ haproxy_cfg.cfg }}
            mode: '0644'
          become: true
