---
- name: 同步所有hosts解析记录
  hosts: all
  become: true
  vars:
    domain: "mslinfo.lan"
    # 定义需要同步的 hosts 解析记录
    host:
      - ip: "10.0.20.173"
        name: "t14"
      - ip: "10.0.10.4"
        name: "pve"
      - ip: "10.0.30.6"
        name: "opse6"
      - ip: "10.0.30.30"
        name: "grafana"
      - ip: "10.0.30.31"
        name: "loki"
      - ip: "10.0.30.33"
        name: "maria"
      - ip: "10.0.30.53"
        name: "dns"
      - ip: "10.0.30.54"
        name: "postgre"
      - ip: "10.0.30.70"
        name: "zabbix"
      - ip: "10.0.30.72"
        name: "prometheus"
      - ip: "10.0.30.101"
        name: "ceph1"
      - ip: "10.0.30.102"
        name: "ceph2"
      - ip: "10.0.30.103"
        name: "ceph3"
      - ip: "10.0.30.110"
        name: "k3s"
      - ip: "10.0.30.111"
        name: "rk1"
      - ip: "10.0.30.112"
        name: "rk2"
      - ip: "10.0.30.113"
        name: "rk3"
      - ip: "10.0.30.110"
        name: "rancher"
      - ip: "10.0.30.116"
        name: "rke2"
      - ip: "10.0.30.117"
        name: "pcs1"
      - ip: "10.0.30.118"
        name: "pcs2"
      - ip: "10.0.30.119"
        name: "pcs3"
      - ip: "10.0.30.120"
        name: "harbor"
      - ip: "10.0.30.129"
        name: "jmpserver"


  tasks:
    - name: 同步hosts解析记录到/etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "{{ item.name }}.{{ domain }}"
        line: "{{ item.ip }} {{ item.name }}.{{ domain }} {{ item.name }}"
        state: present
        create: false
      loop: "{{ host }}"
      become: true
