---
- name: "Install Loki"
  hosts: loki
  become: true
  vars:
    software_name: "loki"
    setup: false
  tasks:
    - name: "在debian类系统上安装{{ software_name }}"
      when: ansible_os_family == "Debian"
      block:
        - name: "在debian类系统上安装{{ software_name }}"
          when: setup is false
          ansible.builtin.apt:
            name: "{{ software_name }}"
            update_cache: true
            state: present
    - name: "在rhel类系统上安装{{ software_name }}"
      when: ansible_os_family == "RedHat"
      block:
        - name: "在rhel类系统上安装{{ software_name }}"
          when: setup is false
          ansible.builtin.dnf:
            name: "{{ software_name }}"
            update_cache: true
            state: present
