---
- name: Install My Linux Desktop
  hosts: all
  become: true
  tasks:
    - name: "Install My Linux Desktop"
      when: ansible_distribution == "Ubuntu"
      block:
        - name: "Add fsearch PPA repository"
          ansible.builtin.apt_repository:
            repo: ppa:fsearch-boxdoerfer/fsearch-stable
            state: present
        - name: "Ubuntu Desktop Installation"
          ansible.builtin.apt:
            pkg:
              - ubuntu-restricted-extras
              - fcitx5-chinese-addons
              - ansible-lint
              - cockpit-pcp
              - containerd
              - golang
              - podman
              - build-essential
              - flatpak
              - git
              - curl
              - vim
              - wget
              - sshuttle
            state: present
            update_cache: true
    - name: 设置flatpak
      when: ansible_distribution == "Ubuntu"
      block:
        - name: 添加官方源
          ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://mirror.sjtu.edu.cn/flathub/flathub.flatpakrepo
