---
- name: Install My Linux Desktop
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "初始化我的工作环境"
      when: ansible_os_family == "Debian"
      block:
        - name: "在ubuntu上移除fsearch PPA repository"
          when: ansible_distribution == "Ubuntu"
          ansible.builtin.apt_repository:
            repo: ppa:christian-boxdoerfer/fsearch-stable
            state: absent
        - name: "Ubuntu Desktop Installation"
          ansible.builtin.apt:
            pkg:
              - ansible-lint
              - build-essential
              - ubuntu-restricted-extras
              - curl
              - cockpit-pcp
              - docker.io
              - docker-compose-v2
              - epiphany-browser
              - golang
              - flatpak
              - fcitx5-chinese-addons
              - fsearch
              - git
              - ptyxis
              - sshuttle
              - tree
              - tealdeer
              - plocate
              - neovim
              - wget
              - https://ishell-down.oss-cn-beijing.aliyuncs.com/ishellpro_3.0.9_amd64.deb
# - sshoot
            state: present
            update_cache: true
        - name: "删除不需要的软件包"
          ansible.builtin.apt:
            pkg:
              - sshoot
              - vim
              - vim-common
              - vim-data
              - vim-doc
              - vim-tiny
            state: absent
    - name: 设置flatpak
      when: ansible_os_family == "Debian"
      block:
        - name: "添加国内flatpak源flathubw"
          community.general.flatpak_remote:
            name: flathub
            flatpakrepo_url: https://mirror.sjtu.edu.cn/flathub/flathub.flatpakrepo
            state: present
          become: true
        - name: "刷新flatpak缓存"
          community.general.flatpak:
            update: true
            refresh: true
          become: true
        - name: "安装flatpak应用"
          community.general.flatpak:
            name: ghcr.io/ansible/community-ansible-dev-tools:latest
            state: present
          become: true
