---
- name: 安装 RKE2 Server
  hosts: all
  vars:
    k8s_version: "1.35.4"
    rke2_version: "v{{ k8s_version }}+rke2r1"
    rke2_token: "123456"
    system_default_registry: "registry.cn-hangzhou.aliyuncs.com"
    rke2_server_lb: rke2.mslinfo.lan
    rke2_server_lb_ip: "10.0.30.116"
    rke2_server_url: "https://{{ rke2_server_lb }}:9345"

  tasks:
    - name: 检查系统是否已经安装此版本的RKE2
      ansible.builtin.shell: |
        rke2 --version | head -1 | awk '{print $3}'
      register: rke2_installed_version
      changed_when: false
    - name: 检查系统是否已经安装此版本的 RKE2结果
      ansible.builtin.debug:
        msg: "检查系统是否已经安装此版本的 RKE2 结果：{{ rke2_installed_version.stdout }}"
    - name: 初始化 RHEL 系系统 (Rocky/AlmaLinux/CentOS/RedHat)
      when: ansible_os_family in ['RedHat'] and rke2_installed_version.stdout != rke2_version
      block:
        - name: 修正时间同步
          ansible.builtin.command: chronyc makestep
          changed_when: false
          become: true
        - name: 安装依赖(RHEL)
          ansible.builtin.dnf:
            name:
              - curl
              - gnupg
              - tar
            state: present
            update_cache: true
          become: true

    - name: 部署 RKE2 Server
      block:
        - name: 创建 RKE2 配置目录
          ansible.builtin.file:
            path: /etc/rancher/rke2
            state: directory
            mode: '0755'
          become: true

        - name: 写入 RKE2 Server 配置文件
          ansible.builtin.copy:
            dest: /etc/rancher/rke2/config.yaml
            mode: '0644'
            content: |
              server: {{ rke2_server_url }}
              token: {{ rke2_token }}
              system-default-registry: {{ system_default_registry }}
              ingress-controller: traefik
              tls-san:
                - {{ rke2_server_lb }}
                - {{ rke2_server_lb_ip }}
          become: true
        - name: 获取 RKE2 安装脚本
          ansible.builtin.uri:
            url: https://rancher-mirror.rancher.cn/rke2/install.sh
            return_content: true
            validate_certs: true
          register: rke2_install_script
        - name: 使用国内镜像安装RKE2
          ansible.builtin.shell: |
            {{ rke2_install_script.content }} | sh -
          args:
            executable: /bin/bash
            warn: false
          environment:
            INSTALL_RKE2_MIRROR: cn
            INSTALL_RKE2_VERSION: "{{ rke2_version }}"
          become: true
          changed_when: true
        - name: 启用并启动 RKE2 Server 服务
          ansible.builtin.systemd:
            name: rke2-server
            enabled: true
            daemon_reload: true
          become: true
